### ISSUE TITLE
Duper incorrectly saturating?

### ISSUE THREAD

**Issue by vlad902** [leanprover-community/duper#34] opened 2024-11-06 21:14 UTC
In [this thread](https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/Duper.20question.3A.20Saturation/near/479733968) you mentioned:

> When calling duper or duper? without setting the portfolio instance, Duper can throw a different error Duper failed to solve the goal and determined that it will be unable to do so with the current configuration of options and selection of premises. If this happens, then Duper saturated or failed on all of the option configurations in its portfolio mode. If this happens on a problem that Vampire can prove, then I would expect you probably found a bug.

Here is an example where I hit that error on something that not only Vampire reaches (actually, this example is derived directly from Vampire output), but that Duper is able to solve without one of the hypotheses included.

In the following reproducer, the `have eq823` fails in the first example, but succeeds in the second without the inclusion of the `eq807` hypothesis.

```lean
import Duper
import Mathlib.Tactic
import Mathlib.Data.Set.Finite

class Magma (α : Type _) where
op : α → α → α
infix:65 " ◇ " => Magma.op

abbrev Equation1701 (G: Type _) [Magma G] := ∀ x y z : G, x = (y ◇ x) ◇ ((z ◇ x) ◇ x)
abbrev Equation1035 (G: Type _) [Magma G] := ∀ x y : G, x = x ◇ ((y ◇ (x ◇ x)) ◇ x)

-- fof(eq3_surj_inj, axiom, ![X] : ?[T] : ( X = mul(T, T) ) => ![T1,T2] : ( (mul(T1, T1) = mul(T2, T2) ) => T1 = T2 ) ).
lemma Finite.eq3_surj_inj (G: Type _) [Magma G] [Finite G] : (∀ X : G, ∃ T : G, X = (T ◇ T)) -> (∀ T1 T2 : G, ((T1 ◇ T1) = (T2 ◇ T2)) -> T1 = T2) := by
  intro ha t1 t2 hb
  let f (t : G) := (t ◇ t)
  let S : Set G := Set.univ
  have m1 : S.MapsTo f S := by
    intro
    simp [S]
  have t : S.SurjOn f S := by
    intro x _
    specialize ha x
    obtain ⟨t, hc⟩ := ha
    use t
    simp [S, f]
    symm
    apply hc
  rw [Set.Finite.surjOn_iff_bijOn_of_mapsTo (Set.toFinite _) m1] at t
  apply t.injOn (by simp [S]) (by simp [S])
  simp only [f, hb]

example (G : Type _) [Magma G] [Finite G] (h : Equation1701 G) : Equation1035 G := by
  have eq807 (X0 : G) : (X0 ◇ (X0 ◇ X0)) = X0 := by duper [h, Finite.eq3_surj_inj]
  have eq823 (X1 X0 : G) : (X0 ◇ X0) = ((X1 ◇ (X0 ◇ X0)) ◇ X0) := by duper [h, eq807, Finite.eq3_surj_inj]
  sorry

example (G : Type _) [Magma G] [Finite G] (h : Equation1701 G) : Equation1035 G := by
  have eq807 (X0 : G) : (X0 ◇ (X0 ◇ X0)) = X0 := by duper [h, Finite.eq3_surj_inj]
  have eq823 (X1 X0 : G) : (X0 ◇ X0) = ((X1 ◇ (X0 ◇ X0)) ◇ X0) := by duper [h, Finite.eq3_surj_inj]
  sorry
```

**Comment by JOSHCLUNE** [comment] 2024-11-06 22:18
This bug is now resolved in the most recent Duper version (v0.0.20). Surprisingly, it turned out to be caused by the same bug as #30.

**Closed by JOSHCLUNE** 2024-11-06 22:18 UTC
